name: Docker Image CI/CD
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - uses: actions/checkout@v1
      - name: Run test
        run: go test ./model
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . -t shu-semester
          docker tag shu-semester ${{ secrets.DOCKER_USERNAME }}/shu-semester:${{ github.sha }}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/shu-semester
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: cloud.shu.xn--io0a7i
          username: root
          password: ${{ secrets.CD_PASSWORD }}
          port: 22
          script: |
            /root/deploy.sh shu-semester ${{ secrets.DOCKER_USERNAME }}/shu-semester:${{ github.sha }}
